@Library('BookmateSharedLibs')_

commonAppDeliveryPipelineProduction_v2(
    scmUrl: 'git@github.com:bookmate/docker-registry-frontend.git',
    appImageName: "infra/docker-registry-frontend",
    services: [[nomadServiceName: 'infra-docker-registry-frontend']],
)

